/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.pomocna.Pretraga;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Nikola
 */
public class FormaPretragaIzdavanja extends javax.swing.JDialog {
    
    JFrame glavnaForma;

    /**
     * Creates new form FormaPretragaIzdavanja
     */
    public FormaPretragaIzdavanja(java.awt.Frame parent, boolean modal,  JFrame gf) {
        super(parent, modal);
        this.glavnaForma=gf;
        initComponents();
        setLocationRelativeTo(null);
        ucitajClanove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbKnjiga = new javax.swing.JRadioButton();
        rbClan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtKnjiga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbClan = new javax.swing.JComboBox();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pretraga izdavanja knjiga");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Izaberite kriterijum po kome želite da izvršite pretragu:");

        buttonGroup1.add(rbKnjiga);
        rbKnjiga.setText("Pretraga po knjizi");

        buttonGroup1.add(rbClan);
        rbClan.setText("Pretraga po članu");

        jLabel3.setText("Unesite naziv knjige:");

        jLabel4.setText("Izaberite člana:");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbClan)
                                    .addComponent(rbKnjiga)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKnjiga)
                                    .addComponent(cmbClan, 0, 317, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(rbKnjiga)
                .addGap(30, 30, 30)
                .addComponent(rbClan)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            validacijaIzbor();
            if(rbKnjiga.isSelected()){
                validacijaKnjige();
                String nazivKnjige = txtKnjiga.getText().trim();
                ArrayList<Pretraga> listaPretraga = pretraziPoKnjizi(nazivKnjige);
                
                new FormaPretrazenaIzdavanjaPoKnjizi(glavnaForma, true, listaPretraga).setVisible(true);
                
            }
            if(rbClan.isSelected()){
                validacijaClana();
                Clan clan = (Clan) cmbClan.getSelectedItem();
                int id=clan.getId();
                ArrayList<Pretraga> listaPretraga = pretraziPoClanu(id);
                
                new FormaPretrazenaIzdavanjaPoClanu(glavnaForma, true, listaPretraga).setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaIzdavanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbClan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbClan;
    private javax.swing.JRadioButton rbKnjiga;
    private javax.swing.JTextField txtKnjiga;
    // End of variables declaration//GEN-END:variables

    private void ucitajClanove() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.UCITAJ_CLANOVE);

        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();

        ArrayList<Clan> listaClanova = (ArrayList<Clan>) so.getOdgovor();
        cmbClan.removeAllItems();
        for (Clan clan : listaClanova) {
            cmbClan.addItem(clan);
        }
        cmbClan.setSelectedIndex(-1);
    }

    private void validacijaIzbor() throws Exception {
        String greska="";
        if(!rbClan.isSelected() && !rbKnjiga.isSelected()){
            greska = "Molimo vas izaberite kriterijum po kome želite da izvršite pretragu.";
        }
        if(!greska.isEmpty()){
            throw new Exception(greska);
        }
    }

    private void validacijaKnjige() throws Exception {
        if(txtKnjiga.getText().trim().isEmpty()){
            throw new Exception("Molimo vas unesite naziv knjige po kojoj želite da pretražite.");
        }
    }

    private void validacijaClana() throws Exception {
        if(cmbClan.getSelectedIndex()<0){
            throw new Exception("Molimo vas izaberite člana po kome želite da pretražite");
        }
    }

    private ArrayList<Pretraga> pretraziPoKnjizi(String nazivKnjige) {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAGA_PO_KNJIZI);
        kz.setParametar(nazivKnjige);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        ArrayList<Pretraga> listaIzdavanja= (ArrayList<Pretraga>) so.getOdgovor();
        return listaIzdavanja;
    }

    private ArrayList<Pretraga> pretraziPoClanu(int id) {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.PRETRAGA_PO_CLANU);
        kz.setParametar(id);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        ArrayList<Pretraga> listaIzdavanja= (ArrayList<Pretraga>) so.getOdgovor();
         return listaIzdavanja;
    }
}
